import React, { useEffect, useState } from 'react'
import PlayerComponent, { Player as PlayerHelper } from './components/Player'

type Track = {
  id: string
  title: string
  artist: string
  thumbnail?: string
  duration?: number
  url?: string
  query?: string
  spotifyUrl?: string
}

type PageKey = 'home' | 'search' | 'recommendations' | 'tracks'

type Locale = 'ru' | 'en'

const dictionary = {
  ru: {
    appTitle: 'FOR YOU',
    subtitle: 'Рекомендации и поиск музыки на основе Spotify',
    home: 'Главная',
    search: 'Поиск',
    recommendations: 'Рекомендации',
    allTracks: 'Все треки',
    spotifyPicks: 'Подборки Spotify',
    discover: 'Открой звук, который подходит твоему настроению.',
    homeDescription: 'Ищи треки и получай обложки и названия из Spotify, а поток запускай через YouTube.',
    searchTracks: 'Поиск треков',
    searchDescription: 'Поиск по метаданным Spotify и воспроизведение подобранного аудио.',
    searchPlaceholder: 'Искать исполнителя, песню или альбом',
    searchButton: 'Поиск',
    recommendationsTitle: 'Рекомендации Spotify',
    recommendationsDescription: 'Свежие треки, сформированные Spotify на основе популярных жанров.',
    refresh: 'Обновить',
    featuredRecommendations: 'Избранные рекомендации',
    whyItWorks: 'Почему это работает',
    whyItWorksDescription: 'Метаданные Spotify дают обложки и правильные названия, а поток сохраняется через подходящий источник.',
    bullet1: '• Правильные названия и артисты из Spotify',
    bullet2: '• Красивые обложки для каждой песни',
    bullet3: '• Интеллектуальные рекомендации от Spotify',
    bullet4: '• Быстрый поиск и плавное воспроизведение',
    allTracksTitle: 'Все треки',
    allTracksDescription: 'Список всех доступных треков из поиска и рекомендаций.',
    recommendedTag: 'Рекомендовано',
    noTracksMessage: 'Пока нет треков для отображения.',
    liked: 'Spotify',
    unknownLength: 'Неизвестно',
    loading: 'Загрузка…',
    selectTrack: 'Выберите трек, чтобы начать',
    tapCard: 'Нажмите на карточку, чтобы воспроизвести'
  },
  en: {
    appTitle: 'FOR YOU',
    subtitle: 'Spotify-powered music recommendations and search',
    home: 'Home',
    search: 'Search',
    recommendations: 'Recommendations',
    allTracks: 'All Tracks',
    spotifyPicks: 'Spotify Picks',
    discover: 'Discover the sound that fits your mood.',
    homeDescription: 'Browse Spotify metadata for artwork, artist names, and track titles, then stream matched audio from YouTube automatically.',
    searchTracks: 'Search Tracks',
    searchDescription: 'Query Spotify metadata and play the best matched audio.',
    searchPlaceholder: 'Search artist, song, or album',
    searchButton: 'Search',
    recommendationsTitle: 'Spotify Recommendations',
    recommendationsDescription: 'Fresh tracks generated by Spotify based on popular seeds.',
    refresh: 'Refresh',
    featuredRecommendations: 'Featured recommendations',
    whyItWorks: 'Why it works',
    whyItWorksDescription: 'Spotify metadata adds rich album artwork and correct track names, while the player source uses search-based streaming to keep your music flowing.',
    bullet1: '• Clean Spotify titles and artists',
    bullet2: '• Beautiful cover artwork for each song',
    bullet3: '• Intelligent recommendations from Spotify',
    bullet4: '• Fast search and responsive playback',
    allTracksTitle: 'All Tracks',
    allTracksDescription: 'Browse all available tracks from search and recommendations.',
    recommendedTag: 'Recommended',
    noTracksMessage: 'No tracks available yet.',
    liked: 'Spotify',
    unknownLength: 'Unknown length',
    loading: 'Loading…',
    selectTrack: 'Choose a track to start',
    tapCard: 'Tap any card to begin listening'
  }
}

export default function App() {
  const [page, setPage] = useState<PageKey>('home')
  const [lang, setLang] = useState<Locale>('ru')
  const [searchQuery, setSearchQuery] = useState('tame')
  const [searchResults, setSearchResults] = useState<Track[]>([])
  const [recommendations, setRecommendations] = useState<Track[]>([])
  const [featured, setFeatured] = useState<Track[]>([])
  const [loading, setLoading] = useState(false)
  const locale = dictionary[lang]

  async function search(q = searchQuery) {
    if (!q) return
    setLoading(true)
    try {
      const res = await fetch(`/api/search?q=${encodeURIComponent(q)}`)
      if (!res.ok) {
        const text = await res.text()
        console.error('Search failed:', res.status, text)
        return
      }
      const contentType = res.headers.get('content-type') || ''
      if (!contentType.includes('application/json')) {
        const text = await res.text()
        console.error('Search returned non-JSON response:', contentType, text)
        return
      }
      const data = await res.json()
      setSearchResults(data)
      setPage('search')
    } catch (err) {
      console.error('Search parse error:', err)
    } finally {
      setLoading(false)
    }
  }

  async function loadRecommendations() {
    try {
      const res = await fetch('/api/spotify/recommendations')
      if (!res.ok) {
        const text = await res.text()
        console.error('Recommendations failed:', res.status, text)
        return
      }
      const contentType = res.headers.get('content-type') || ''
      if (!contentType.includes('application/json')) {
        const text = await res.text()
        console.error('Recommendations returned non-JSON response:', contentType, text)
        return
      }
      const data = await res.json()
      setRecommendations(data)
      setFeatured(data.slice(0, 6))
    } catch (err) {
      console.error('Recommendations parse error:', err)
    }
  }

  useEffect(() => {
    void loadRecommendations()
    void search(searchQuery)
  }, [])

  const pages = [
    { key: 'home' as PageKey, label: locale.home },
    { key: 'search' as PageKey, label: locale.search },
    { key: 'recommendations' as PageKey, label: locale.recommendations },
    { key: 'tracks' as PageKey, label: locale.allTracks }
  ]

  const allTracks = Array.from(
    new Map([...recommendations, ...searchResults].map((track) => [track.id, track])).values()
  )

  return (
    <div className="min-h-screen bg-background text-on-background pb-32">
      <header className="w-full top-0 sticky z-40 bg-background border-b border-slate-200/60 py-4">
        <div className="max-w-6xl mx-auto px-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-4">
            <span className="material-symbols-outlined text-3xl">headphones</span>
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight">{locale.appTitle}</h1>
              <p className="text-sm text-slate-600">{locale.subtitle}</p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <nav className="flex flex-wrap gap-2">
              {pages.map((item) => (
                <button
                  key={item.key}
                  onClick={() => setPage(item.key)}
                  className={`rounded-full px-4 py-2 text-sm font-semibold transition ${page === item.key ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`}
                >
                  {item.label}
                </button>
              ))}
            </nav>
            <div className="flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 p-1">
              <button
                onClick={() => setLang('ru')}
                className={`rounded-full px-3 py-1 text-sm font-semibold ${lang === 'ru' ? 'bg-slate-950 text-white' : 'text-slate-600'}`}
              >RU</button>
              <button
                onClick={() => setLang('en')}
                className={`rounded-full px-3 py-1 text-sm font-semibold ${lang === 'en' ? 'bg-slate-950 text-white' : 'text-slate-600'}`}
              >EN</button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-6 space-y-8">
        {page === 'home' && (
          <section className="space-y-6">
            <div className="rounded-[28px] bg-slate-950 text-white p-8 shadow-xl overflow-hidden relative">
              <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/20 via-transparent to-slate-900/80" />
              <div className="relative grid gap-6 md:grid-cols-[1.4fr_0.8fr] items-center">
                <div>
                  <div className="text-sm uppercase tracking-[0.32em] text-cyan-300/80 font-semibold mb-4">{locale.spotifyPicks}</div>
                  <h2 className="text-4xl font-black tracking-tight">{locale.discover}</h2>
                  <p className="mt-4 max-w-2xl text-slate-300">{locale.homeDescription}</p>
                  <div className="mt-6 flex flex-wrap gap-3">
                    <button onClick={() => setPage('search')} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950 shadow-lg hover:bg-slate-100 transition">{locale.search}</button>
                    <button onClick={() => setPage('recommendations')} className="rounded-full border border-white/20 px-5 py-3 text-sm text-white hover:bg-white/10 transition">{locale.recommendations}</button>
                  </div>
                </div>
                <div className="rounded-3xl border border-white/10 p-5 bg-white/5 backdrop-blur-lg">
                  <div className="grid grid-cols-3 gap-3">
                    {featured.map((track) => (
                      <div key={track.id} className="aspect-square rounded-3xl overflow-hidden bg-slate-800">
                        <img src={track.thumbnail || `https://i.ytimg.com/vi/${track.id}/hqdefault.jpg`} alt={track.title} className="h-full w-full object-cover" />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-3xl bg-white p-6 shadow-sm border border-slate-200">
                <h3 className="text-xl font-semibold mb-3">{locale.featuredRecommendations}</h3>
                <div className="grid gap-3">
                  {recommendations.slice(0, 4).map((track) => (
                    <button key={track.id} onClick={() => PlayerHelper.playTrackExtern(track)} className="flex items-center gap-4 rounded-3xl border border-slate-200 p-4 text-left hover:bg-slate-50 transition">
                      <img src={track.thumbnail || `https://i.ytimg.com/vi/${track.id}/hqdefault.jpg`} alt={track.title} className="h-16 w-16 rounded-2xl object-cover" />
                      <div className="min-w-0">
                        <div className="font-semibold truncate">{track.title}</div>
                        <div className="text-sm text-slate-500 truncate">{track.artist}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              <div className="rounded-3xl bg-slate-950 text-white p-6 shadow-xl">
                <h3 className="text-xl font-semibold mb-3">{locale.whyItWorks}</h3>
                <p className="text-slate-300">{locale.whyItWorksDescription}</p>
                <ul className="mt-4 space-y-3 text-slate-300">
                  <li>{locale.bullet1}</li>
                  <li>{locale.bullet2}</li>
                  <li>{locale.bullet3}</li>
                  <li>{locale.bullet4}</li>
                </ul>
              </div>
            </div>
          </section>
        )}

        {page === 'search' && (
          <section className="space-y-6">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold">{locale.searchTracks}</h2>
                <p className="mt-2 text-sm text-slate-600">{locale.searchDescription}</p>
              </div>
              <div className="flex flex-col gap-3 sm:flex-row">
                <input
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder={locale.searchPlaceholder}
                  className="w-full min-w-[240px] rounded-full border border-slate-300 px-5 py-3 shadow-sm focus:border-slate-500 focus:outline-none"
                />
                <button onClick={() => void search(searchQuery)} className="rounded-full bg-slate-950 px-5 py-3 text-white shadow-sm hover:bg-slate-800 transition">{loading ? locale.loading : locale.searchButton}</button>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {searchResults.map((track) => (
                <button key={track.id} onClick={() => PlayerHelper.playTrackExtern(track)} className="group rounded-3xl overflow-hidden border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-md">
                  <div className="relative h-56 overflow-hidden bg-slate-100">
                    <img src={track.thumbnail || `https://i.ytimg.com/vi/${track.id}/hqdefault.jpg`} alt={track.title} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" />
                  </div>
                  <div className="p-4">
                    <div className="font-semibold truncate">{track.title}</div>
                    <div className="mt-1 text-sm text-slate-500 truncate">{track.artist}</div>
                    <div className="mt-4 flex items-center justify-between text-xs text-slate-400">
                      <span>{track.duration ? `${Math.floor(track.duration / 60)}:${String(track.duration % 60).padStart(2, '0')}` : locale.unknownLength}</span>
                      <span className="rounded-full bg-slate-100 px-3 py-1">{locale.liked}</span>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </section>
        )}

        {page === 'recommendations' && (
          <section className="space-y-6">
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold">{locale.recommendationsTitle}</h2>
                <p className="mt-2 text-sm text-slate-600">{locale.recommendationsDescription}</p>
              </div>
              <button onClick={() => void loadRecommendations()} className="rounded-full border border-slate-300 px-5 py-3 text-slate-700 hover:bg-slate-100 transition">{locale.refresh}</button>
            </div>

            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {recommendations.map((track) => (
                <button key={track.id} onClick={() => PlayerHelper.playTrackExtern(track)} className="flex flex-col rounded-3xl overflow-hidden border border-slate-200 bg-white shadow-sm text-left hover:-translate-y-1 hover:shadow-md transition">
                  <div className="h-56 overflow-hidden bg-slate-100">
                    <img src={track.thumbnail || `https://i.ytimg.com/vi/${track.id}/hqdefault.jpg`} alt={track.title} className="h-full w-full object-cover" />
                  </div>
                  <div className="p-4">
                    <div className="font-semibold truncate">{track.title}</div>
                    <div className="mt-1 text-sm text-slate-500 truncate">{track.artist}</div>
                    <div className="mt-3 flex items-center justify-between text-xs text-slate-400">
                      <span>{track.duration ? `${Math.floor(track.duration / 60)}:${String(track.duration % 60).padStart(2, '0')}` : locale.unknownLength}</span>
                      <span className="rounded-full bg-slate-100 px-3 py-1">{locale.recommendedTag}</span>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </section>
        )}

        {page === 'tracks' && (
          <section className="space-y-6">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold">{locale.allTracksTitle}</h2>
                <p className="mt-2 text-sm text-slate-600">{locale.allTracksDescription}</p>
              </div>
            </div>

            {allTracks.length === 0 ? (
              <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center text-slate-500">{locale.noTracksMessage}</div>
            ) : (
              <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                {allTracks.map((track) => (
                  <button key={track.id} onClick={() => PlayerHelper.playTrackExtern(track)} className="group rounded-3xl overflow-hidden border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-md">
                    <div className="relative h-56 overflow-hidden bg-slate-100">
                      <img src={track.thumbnail || `https://i.ytimg.com/vi/${track.id}/hqdefault.jpg`} alt={track.title} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" />
                    </div>
                    <div className="p-4">
                      <div className="font-semibold truncate">{track.title}</div>
                      <div className="mt-1 text-sm text-slate-500 truncate">{track.artist}</div>
                      <div className="mt-4 flex items-center justify-between text-xs text-slate-400">
                        <span>{track.duration ? `${Math.floor(track.duration / 60)}:${String(track.duration % 60).padStart(2, '0')}` : locale.unknownLength}</span>
                        <span className="rounded-full bg-slate-100 px-3 py-1">{locale.liked}</span>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </section>
        )}
      </main>

      <PlayerComponent />
    </div>
  )
}
